"""Alembic environment, generated by ``eventkit db init``.

``__EVENTKIT_PACKAGE__`` is substituted with the app's package name at
generation time; that package must expose a top-level ``target_metadata``
attribute (typically ``target_metadata = Base.metadata`` next to the app's
declarative ``Base``, built with :func:`eventkit.db.declarative_base`).

Do not hand-edit ``run_migrations_online``'s ``engine_from_config`` fallback
without reading :mod:`eventkit.db.migrate`: :func:`upgrade_to_head` passes its
already-configured ``Database.engine`` through ``config.attributes["engine"]``
so a migration runs through the same pool and pragmas (``AZURE_FILES_PRAGMAS``,
if configured) as the application itself. Only a bare ``alembic upgrade head``
invoked by hand falls through to building a fresh engine from ``DATABASE_URL``
/ ``sqlalchemy.url``.
"""

from __future__ import annotations

import os
from logging.config import fileConfig

from __EVENTKIT_PACKAGE__ import target_metadata
from alembic import context
from sqlalchemy import engine_from_config, pool

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)


def get_url() -> str:
    return os.environ.get("DATABASE_URL") or config.get_main_option("sqlalchemy.url")


def run_migrations_offline() -> None:
    context.configure(
        url=get_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        render_as_batch=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = config.attributes.get("engine")
    if connectable is None:
        connectable = engine_from_config(
            {"sqlalchemy.url": get_url()},
            prefix="sqlalchemy.",
            poolclass=pool.NullPool,
        )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_as_batch=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
